language: cpp
sudo: required
dist: trusty

os: linux

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  - sudo apt-get update -qq
  - git clone https://github.com/NixOS/patchelf.git
  - cd patchelf
  - bash ./bootstrap.sh
  - ./configure
  - make -j2
  - sudo make install
  - cd -
  - sudo wget -c "https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O /usr/local/bin/appimagetool
  - sudo chmod a+x /usr/local/bin/appimagetool
  
install:
  - sudo apt-get -y install qt57base binutils

script:
  - source /opt/qt57/bin/qt57-env.sh
  - /opt/qt57/bin/qmake linuxdeployqt.pro
  - make -j2
  - mkdir -p linuxdeployqt.AppDir/usr/bin/
  - cp /usr/local/bin/patchelf linuxdeployqt.AppDir/usr/bin/
  - cp /usr/local/bin/appimagetool linuxdeployqt.AppDir/usr/bin/
  - cp ./linuxdeployqt/linuxdeployqt linuxdeployqt.AppDir/usr/bin/linuxdeployqt
  - strip linuxdeployqt.AppDir/usr/bin/* || continue
  - export VERSION=continuousfhs
  - ./linuxdeployqt/linuxdeployqt linuxdeployqt.AppDir/usr/bin/linuxdeployqt -verbose=3 -appimage
  - ls -lh
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh ./linuxdeployqt-*.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
