language: cpp
sudo: required
dist: trusty

os: linux

env:
  global:
    - DISPLAY=:99

before_install:
  - ./tests/tests-environment.sh

script:
 - ./tests/tests-ci.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh ./linuxdeployqt-*.AppImage

after_script:
  - "xpra stop :99"

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

notifications:
  irc:
    channels:
      - "chat.freenode.net#AppImage"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
    template:
      - "%{repository} build %{build_number}: %{result} %{build_url}"
    use_notice: true
    # skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4bf20518805a55998cc2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
